spring:
  application:
    name: quoting_service

server:
  base-path: /vk_bot

vk:
  token: myToken
  api_version: 5.199
  message_template: "Вы сказали: %s"
  confirmation:
    group_id: 226335516
    code: ENC(E1JMv7KUdwLMzN8jwDst9iH3b78DeVJFQkLGFmIlg9I=)
