spring:
  application:
    name: quoting-vk-bot

server:
  base-path: /vk_bot

vk:
  token: ENC(AMOzCohxSnvHTvoMdgH+eJyrN98nS25bs9Qw7xlWgHb882sfXGwFSM0UXWiPlD7usIsR7MBV4xg4jpKQYkquXXc6s1Vau97LZ4We3S9Xqs3Q0U4m0JFMHb6tzo9I0DgvMplYOUtIpbWgq/qyA95JuKSG3f+nCYYPnAnSHgl4HEwAK9boTyiLur9uazXjckWef7cQggHW+GnRTtA0iDLqgV3a0n/EmmlrTsrT3i3wsThoqnXmZPIzfRw5acdd2mRzhrlJJoNjW4eKLMkSZmZIjrNJZ4of+eK9VjyvQwjODilW0vedrIl0SR46BDYHpabW)
  api_version: 5.199
  message_template: "Вы сказали: %s"
  confirmation:
    group_id: 226335516
    code: ENC(E1JMv7KUdwLMzN8jwDst9iH3b78DeVJFQkLGFmIlg9I=)

jasypt:
  encryptor:
    password: ${VK_JASYPT_SECRET}
    algorithm: PBEWithMD5AndDES